export { default as Banner } from './Banner'
export { default as NewArrivals } from './NewArrivals'
export { default as NewOffers } from './NewOffers'
export { default as Popularcategories } from './Popularcategories'
export { default as LatestBlogs } from './LatestBlogs'